name: 'Unit Tests'

on:
  push:
    paths:
      - '.github/workflows/unit-tests.yml'
      - '**/*.js'

jobs:
  unit-tests:
    name: 'Unit tests'
    runs-on: 'ubuntu-20.04'
    steps:
      - name: 'Clone the repository'
        uses: 'actions/checkout@v2'

      - name: 'Install dependencies'
        run: 'yarn'

      - name: 'Run unit tests'
        run: 'yarn test'
